services:
  backend:
    build:
      context: ./Backend
      dockerfile: API/Dockerfile
    ports:
      - "9090:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network

  flutterweb:
    build:
      context: ./flutter_app
      dockerfile: Dockerfile
    ports:
      - "9091:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
